### ISSUE TITLE
Incorrect PSNR calculation caused by subtraction of np.ndarray with dtype=np.uint8

### ISSUE THREAD

**Issue by DreamChaserMXF** [DevKiHyun/VDSR-Tensorflow#1]
Hi!
It's good to see the implementation of VDSR in python3 with TensorFlow, since almost every repo of VDSR with TensorFlow I've found on github is using python2.
However, when I checked the PSNR calculation function in utils.py, I noticed that the input arguments x and y were not converted to float numbers, which are necessary to ensure the correctness of subtraction between x and y. In fact, when you pass x and y with type of numpy.ndarray and dtype=numpy.uint8, the pixel subtraction result `a - b` will be **zero** if a is less than b. This will cause a smaller `rmse` , which means a higher (but wong) PSNR.
Nonetheless, I'm very appreciate your effort since this repo has a nice structure and the code is easy to run.

**Comment by DevKiHyun** [comment]
Thank you. I agree with your opinion. I am going to fix this problem in this week.

**Comment by DevKiHyun** [comment]
I updated psnr function in util.py. If you no longer have any questions, I will close the issue.

**Comment by DreamChaserMXF** [comment]
No problem :-)
