### ISSUE TITLE
input data for training

### ISSUE THREAD

**Issue by lehy786** [DevKiHyun/VDSR-Tensorflow#2]
Hi, thank you for sharing this project firstly. I met some problem when I  was learning your codes. I found the train.py set training data like this:
    '''
    DATA SET PATH
    '''
    train_x_images_path = '{}/data/train_291_input/*.npy'.format(main_data_path)
    train_y_images_path = '{}/data/train_291_label/*.npy'.format(main_data_path)
    test_labels_path = '{}/data/Set5/ground_truth/*.npy'.format(main_data_path)
    test_inputs_path = '{}/data/Set5/blur_{}x/*.npy'.format(main_data_path, default_test_scale)

That should means the training data are pre-handled. So, where can I found those images? 
Thanks for a lot.

**Comment by DevKiHyun** [comment]
Hi, lehy786. I read my readme and I found that I missed an explain of pre-processing step. So, I added it now. If you use my github, then you should follow  the readme. Thank you for read my github ^^

**Comment by DevKiHyun** [comment]
And answer your question, 

'''
DATA SET PATH
'''
train_x_images_path = '{}/data/train_291_input/.npy'.format(main_data_path)
train_y_images_path = '{}/data/train_291_label/.npy'.format(main_data_path)
test_labels_path = '{}/data/Set5/ground_truth/.npy'.format(main_data_path)
test_inputs_path = '{}/data/Set5/blur_{}x/.npy'.format(main_data_path, default_test_scale)

Right, this means the training data are pre-handled. You can find this pre-processed training images by following pre-processing step in readme. And I will upload pre-processed dataset on google drive. If your question is resolved, please close this issue. : )

**Comment by lehy786** [comment]
sorry for the late. This is my first time answer, I didn't realized the issue need to be closed. Hahaha~.
