### ISSUE TITLE
the bug of aug_test.m

### ISSUE THREAD

**Issue by violetsaturn** [DevKiHyun/VDSR-Tensorflow#3]
hi, thank you for you writing the code of VDSR, I found a mistake in the file of aug_test.m, it is said
'no define the 'folder_y_ch'', Cloud you help me to solve this problem?
thank you

**Comment by DevKiHyun** [comment]
@violetsaturn
Hi! Thank you for read my github and tell me my bug! The 'folder_y_ch' should be 'folder_label'.
So, I fixed my code now. Thank you!

**Comment by violetsaturn** [comment]
OK，it is so kind of you and wish you have a happy day!
